### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by Seektruth321** [TangZJ/3iGS#1]
Hello, what is the purpose of the -w in your training instruction?

**Comment by TangZJ** [comment]
It’s a feature from 3dgs:

“
--white_background / -w
<https://github.com/graphdeco-inria/gaussian-splatting#--white_background---w>

Add this flag to use white background instead of black (default), e.g., for
evaluation of NeRF Synthetic dataset.

“

**Comment by Seektruth321** [comment]
Thanks for your guidance

**Comment by 2693748650** [comment]
请问您的代码里面包括计算法线吗。每次我加入法线计算loss都会变成none
